moon:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: LefttoRight
    pid: {p: 1000.0, i: 0.1, d: 50}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: fore
    pid: {p: 5000.0, i: 0, d: 1000 }
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: aft
    pid: {p: 5000.0, i: 0, d: 1000}

  joint5_position_controller:
    type: effort_controllers/JointVelocityController
    joint: aftRightTire_j
    pid: {p: 500.0, i: 0, d: 0}
  joint6_position_controller:
    type: effort_controllers/JointVelocityController
    joint: aftLeftTire_j
    pid: {p: 500.0, i: 0, d: 0}
  joint7_position_controller:
    type: effort_controllers/JointVelocityController
    joint: midRightTire_j
    pid: {p: 500.0, i: 0, d: 0}
  joint8_position_controller:
    type: effort_controllers/JointVelocityController
    joint: foreRightTire_j
    pid: {p: 500.0, i: 0, d: 0}
  joint9_position_controller:
    type: effort_controllers/JointVelocityController
    joint: foreLeftTire_j
    pid: {p: 500.0, i: 0, d: 0}
  joint10_position_controller:
    type: effort_controllers/JointVelocityController
    joint: midLeftTire_j
    pid: {p: 500.0, i: 0, d: 0}
