moon:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  

  # Position Controllers ---------------------------------------
  LefttoRight:
    type: effort_controllers/JointPositionController
    joint: LefttoRight
    pid: {p: 1000.0, i: 0.1, d: 50}
  fore:
    type: effort_controllers/JointPositionController
    joint: fore
    pid: {p: 5000.0, i: 0, d: 1000 }
  aft:
    type: effort_controllers/JointPositionController
    joint: aft
    pid: {p: 5000.0, i: 0, d: 1000}

  aftRightWheel_j:
    type: effort_controllers/JointVelocityController
    joint: aftRightWheel_j
    pid: {p: 500.0, i: 0, d: 0}
  aftLeftWheel_j:
    type: effort_controllers/JointVelocityController
    joint: aftLeftWheel_j
    pid: {p: 500.0, i: 0, d: 0}
  midRightWheel_j:
    type: effort_controllers/JointVelocityController
    joint: midRightWheel_j
    pid: {p: 500.0, i: 0, d: 0}
  foreRightWheel_j:
    type: effort_controllers/JointVelocityController
    joint: foreRightWheel_j
    pid: {p: 500.0, i: 0, d: 0}
  foreLeftWheel_j:
    type: effort_controllers/JointVelocityController
    joint: foreLeftWheel_j
    pid: {p: 500.0, i: 0, d: 0}
  midLeftWheel_j:
    type: effort_controllers/JointVelocityController
    joint: midLeftWheel_j
    pid: {p: 500.0, i: 0, d: 0}
